#!/usr/bin/env bash
# punto 0

ERR="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

[[ $# != 4 ]] && echo "$ERR" && exit

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":/home/"$3"
