#!/usr/bin/env bash
# configures a new ubuntu machine Ngix

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
