#!/usr/bin/env bash
# Serve a web page using nginx


LINE="\\\trewrite ^/redirect_me https://github.com/jparrales permanent;"
sed -i "24i $LINE" /etc/nginx/sites-available/default

service nginx restart