#!/usr/bin/env bash
# Serve a web page using nginx

echo "Ceci n'est pas une page"  > /var/www/html/404.html

#redirect
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/html/; internal; }' /etc/nginx/sites-enabled/default

service nginx restart
