#!/usr/bin/env bash
# Serve a web page using nginx

sudo service nginx restart
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html

REDIRECT='\\trewrite ^/redirect_me https://github.com/jparrales permanent;'
filePath='/etc/nginx/sites-available/default'
sed -i '20i\\t#Permanent redirects' $filePath
sed -i '21i\\t#' $filePath
sed -i "22i $REDIRECT" $filePath
sed -i '23i \\t' $filePath

echo -e "Ceci n'est pas une pagei\n" | sudo tee /var/www/html/404.html

sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/html/; internal; }' $filePath

service nginx restart
