#!/usr/bin/env bash
# Serve a web page using nginx

apt-get update
apt-get -y install haproxy

cat <<EOM >> /etc/haproxy/haproxy.cfg

frontend 1535-lb-01
    bind *:80
    mode http
    option forwardfor
    default_backend servers

backend servers
    balance roundrobin
    server web-01 34.73.45.95
    server web-02 34.75.190.51

EOM

sudo service haproxy start
