#!/usr/bin/env bash
# This script is display information about the holbertonschool file

file="holbertonschool"

if [ ! -e $file ]
then
	echo "holbertonschool file does not exist"
	exit 0
fi

echo "holbertonschool file exists"

if [ -s $file ]
then
	echo "holbertonschool file is not empty"
else
	echo "holbertonschool file is empty"
fi

if [ ! -d $file ]
then
	echo "holbertonschool is a regular file"
fi
