#!/usr/bin/env bash
# This script is display information about the holbertonschool file

file="holbertonschool"

if [ ! -e $file ]
then
	echo "holbertonschool file does not exist"
	exit 0
else
	echo "holbertonschool file exist"

	if [ ! -s $file ]
	then
		echo "holbertonschool file is empty"
	else
		echo "holbertonschool file is not empty"
	fi
	
	if [ ! -d $file ]
	then
		echo "holbertonschool is a regular file"
	fi
fi
